apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: monolithic
  name: monolithic
spec:
  containers:
  - image: memcached
    name: monolithic
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
